import { useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { ScrollView, Text, TextInput } from 'react-native';
import type { ISODateTime } from '@/domain';
import { LocalFoodCorpus, openMeatDatabase, SqliteFoodRepository, SqliteMealRepository } from '@/data';
import { FoodLoggingService, defaultLocalIdFactory } from '@/services/logging/food-logging';
import { ActionButton, Surface, spacing, typography, useThemeColors } from '@/ui';

const numberOrUndefined=(value:string)=>value.trim()===''?undefined:Number(value);
export default function ManualFoodScreen(){
 const colors=useThemeColors(),router=useRouter();const[service,setService]=useState<FoodLoggingService|null>(null);const[name,setName]=useState(''),[serving,setServing]=useState('100'),[calories,setCalories]=useState(''),[protein,setProtein]=useState(''),[carbs,setCarbs]=useState(''),[fat,setFat]=useState(''),[fiber,setFiber]=useState(''),[message,setMessage]=useState<string|null>(null);
 useEffect(()=>{void openMeatDatabase().then((db)=>setService(new FoodLoggingService(new LocalFoodCorpus(db),new SqliteFoodRepository(db),new SqliteMealRepository(db),defaultLocalIdFactory))).catch((e:unknown)=>setMessage(e instanceof Error?e.message:'Unable to open database.'))},[]);
 async function save(){if(!service)return;try{const servingGrams=Number(serving);const values={calories:numberOrUndefined(calories),protein:numberOrUndefined(protein),carbohydrate:numberOrUndefined(carbs),fat:numberOrUndefined(fat),fiber:numberOrUndefined(fiber)};if(Object.values(values).some((v)=>v!==undefined&&!Number.isFinite(v))){setMessage('Nutrition values must be numbers.');return}const food=await service.createManualFood({name,servingGrams,...values},new Date().toISOString() as ISODateTime);await service.logFood(food,servingGrams,new Date().toISOString() as ISODateTime);router.replace('/') }catch(e){setMessage(e instanceof Error?e.message:'Unable to save food.')}}
 const field=(label:string,value:string,set:(v:string)=>void)=><TextInput key={label} accessibilityLabel={label} placeholder={label} placeholderTextColor={colors.textSecondary} keyboardType={label==='Food name'?'default':'decimal-pad'} value={value} onChangeText={set} style={[typography.body,{color:colors.textPrimary,borderColor:colors.border,borderWidth:1,borderRadius:12,padding:12}]} />;
 return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{padding:spacing.md,gap:spacing.md,backgroundColor:colors.background}} keyboardShouldPersistTaps="handled"><Text allowFontScaling selectable style={[typography.title1,{color:colors.textPrimary}]}>Manual food</Text><Surface>{field('Food name',name,setName)}{field('Serving grams',serving,setServing)}{field('Calories per serving',calories,setCalories)}{field('Protein grams per serving',protein,setProtein)}{field('Carbohydrate grams per serving',carbs,setCarbs)}{field('Fat grams per serving',fat,setFat)}{field('Fiber grams per serving',fiber,setFiber)}<Text allowFontScaling selectable style={[typography.caption,{color:colors.textSecondary}]}>Leave an unknown nutrient blank. A blank value is not stored as zero.</Text><ActionButton label="Save and log" onPress={()=>void save()} disabled={!service||!name.trim()} /></Surface>{message?<Text accessibilityLiveRegion="polite" selectable style={[typography.body,{color:colors.destructive}]}>{message}</Text>:null}</ScrollView>
}
